const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/pages/Stock.jsx');
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/import '\.\/Stock\.css';\r?\n?/, '');

const classesMap = {
  'className="stk-page"': 'className="min-h-[calc(100vh-64px)] bg-transparent p-5 md:p-8 flex flex-col gap-6 font-sans"',
  'className="stk-loading"': 'className="flex flex-col items-center justify-center min-h-[60vh] gap-4"',
  'className="stk-loading-spinner"': 'className="w-10 h-10 border-[3px] border-muted border-t-primary rounded-full animate-spin"',
  'className="stk-header"': 'className="relative p-8 overflow-hidden border border-border/80 rounded-[28px] bg-gradient-to-b from-white/98 to-slate-50/96 shadow-sm"',
  'className="stk-header-bg"': 'className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(27,94,32,0.12)_0%,transparent_34%),linear-gradient(135deg,rgba(27,94,32,0.04)_0%,rgba(255,214,0,0.03)_50%,rgba(211,47,47,0.02)_100%)] pointer-events-none"',
  'className="stk-header-content"': 'className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-6"',
  'className="stk-header-left"': 'className="flex items-center gap-5"',
  'className="stk-header-icon"': 'className="w-12 h-12 flex items-center justify-center bg-gradient-to-br from-primary to-secondary text-white rounded-xl shadow-[0_6px_20px_rgba(27,94,32,0.25)] shrink-0"',
  '<h1>Gestion du Stock</h1>': '<h1 className="text-2xl font-extrabold text-foreground tracking-tight m-0 mb-0.5 leading-tight">Gestion du Stock</h1>',
  '<p>Suivez votre inventaire et gérez vos entrées de stock</p>': '<p className="text-[0.85rem] font-medium text-muted-foreground m-0">Suivez votre inventaire et gérez vos entrées de stock</p>',
  'className="stk-btn-entree"': 'className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-br from-[#D32F2F] to-[#b71c1c] text-white border-none rounded-2xl text-[0.88rem] font-bold cursor-pointer transition-all shadow-lg hover:-translate-y-0.5 hover:shadow-xl hover:shadow-accent/30 whitespace-nowrap"',
  'className="stk-stats"': 'className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"',
  'className="stk-stat-card"': 'className="relative flex items-center gap-4 p-5 bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-[22px] shadow-sm transition-all overflow-hidden hover:-translate-y-1 hover:shadow-md before:absolute before:top-0 before:left-[1.1rem] before:right-[1.1rem] before:h-[3px] before:rounded-full before:bg-gradient-to-r before:from-primary before:to-secondary"',
  'className="stk-stat-icon blue"': 'className="w-12 h-12 flex items-center justify-center rounded-xl shrink-0 bg-[#D32F2F]/10 text-[#D32F2F]"',
  'className="stk-stat-icon green"': 'className="w-12 h-12 flex items-center justify-center rounded-xl shrink-0 bg-[#1B6B3A]/10 text-[#1B6B3A]"',
  'className="stk-stat-icon amber"': 'className="w-12 h-12 flex items-center justify-center rounded-xl shrink-0 bg-amber-500/10 text-amber-500"',
  'className="stk-stat-icon purple"': 'className="w-12 h-12 flex items-center justify-center rounded-xl shrink-0 bg-[#D4880F]/10 text-[#D4880F]"',
  'className="stk-stat-info"': 'className="flex flex-col min-w-0"',
  'className="stk-stat-value"': 'className="text-[1.15rem] font-extrabold text-foreground tracking-tight whitespace-nowrap overflow-hidden text-ellipsis"',
  'className="stk-stat-value stk-alert-val"': 'className="text-[1.15rem] font-extrabold text-amber-500 tracking-tight whitespace-nowrap overflow-hidden text-ellipsis"',
  'className="stk-stat-label"': 'className="text-[0.76rem] font-semibold text-muted-foreground mt-0.5"',
  'className="stk-toolbar"': 'className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-4 bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-[22px] shadow-sm"',
  'className="stk-tabs"': 'className="flex bg-gradient-to-b from-slate-100/95 to-slate-200/75 border border-border/80 rounded-2xl p-1 gap-0.5 shadow-inner"',
  'className={`stk-tab ${tab === \'inventaire\' ? \'active\' : \'\'}`}': 'className={`inline-flex items-center gap-1.5 px-4 py-2 border-none rounded-xl text-[0.82rem] font-semibold cursor-pointer transition-all ${tab === \'inventaire\' ? \'bg-white text-foreground shadow-sm\' : \'bg-transparent text-muted-foreground hover:text-foreground\'}`}',
  'className={`stk-tab ${tab === \'historique\' ? \'active\' : \'\'}`}': 'className={`inline-flex items-center gap-1.5 px-4 py-2 border-none rounded-xl text-[0.82rem] font-semibold cursor-pointer transition-all ${tab === \'historique\' ? \'bg-white text-foreground shadow-sm\' : \'bg-transparent text-muted-foreground hover:text-foreground\'}`}',
  'className="stk-tab-count"': 'className="inline-flex items-center justify-center px-2 py-0.5 bg-muted rounded-full text-[0.68rem] font-bold text-muted-foreground min-w-[20px] ml-1"',
  'className="stk-search"': 'className="flex items-center gap-2 px-4 py-2 bg-slate-50/90 border border-border/80 rounded-2xl min-w-[240px] transition-all shadow-inner focus-within:border-primary focus-within:shadow-[0_0_0_4px_rgba(27,94,32,0.08)]"',
  'className="stk-content"': 'className="p-0"',
  'className="stk-table-card"': 'className="bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-3xl overflow-x-auto shadow-sm relative backdrop-blur-md before:absolute before:inset-x-0 before:top-0 before:h-[3px] before:bg-gradient-to-r before:from-primary before:to-secondary"',
  'className="stk-table"': 'className="w-full border-collapse min-w-[800px] text-left"',
  '<thead>\n                <tr>': '<thead className="bg-gradient-to-b from-slate-50/98 to-slate-100/95 border-b border-border">\n                <tr>',
  '<th scope="col">Produit</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Produit</th>',
  '<th scope="col">Catégorie</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Catégorie</th>',
  '<th scope="col">Stock</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Stock</th>',
  '<th scope="col">Unité</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Unité</th>',
  '<th scope="col">Valeur Stock</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Valeur Stock</th>',
  '<th scope="col">Statut</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Statut</th>',
  '<th scope="col">Date</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Date</th>',
  '<th scope="col">Quantité</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Quantité</th>',
  '<th scope="col">Prix Achat</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Prix Achat</th>',
  '<th scope="col">Fournisseur</th>': '<th scope="col" className="px-5 py-3.5 text-[0.72rem] font-bold text-muted-foreground uppercase tracking-wider">Fournisseur</th>',
  'className={p.enAlerte ? \'stk-row-alert\' : \'\'}': 'className={`transition-all hover:bg-muted/50 hover:translate-x-0.5 border-b border-muted last:border-0 ${p.enAlerte ? \'bg-amber-500/5 hover:bg-amber-500/10\' : \'\'}`}',
  '<tr key={e.id}>': '<tr key={e.id} className="transition-all hover:bg-muted/50 hover:translate-x-0.5 border-b border-muted last:border-0">',
  '<th scope="row">': '<th scope="row" className="px-5 py-4 font-normal align-middle">',
  '<td>': '<td className="px-5 py-4 align-middle">',
  'className="stk-product-cell"': 'className="flex items-center gap-2.5"',
  'className="stk-product-avatar"': 'className="w-8 h-8 flex items-center justify-center bg-primary/10 text-primary rounded-[10px] shrink-0 shadow-sm"',
  'className="stk-product-avatar green"': 'className="w-8 h-8 flex items-center justify-center bg-[#1B6B3A]/10 text-[#1B6B3A] rounded-[10px] shrink-0 shadow-sm"',
  '<strong>{p.nom}</strong>': '<strong className="font-bold text-foreground">{p.nom}</strong>',
  '<strong>{e.produit?.nom}</strong>': '<strong className="font-bold text-foreground">{e.produit?.nom}</strong>',
  'className="stk-cat-badge"': 'className="inline-block px-2.5 py-1 bg-muted rounded-full text-[0.76rem] font-semibold text-muted-foreground"',
  'className={`stk-stock-val ${p.enAlerte ? \'alert\' : \'\'}`}': 'className={`font-extrabold text-[0.92rem] ${p.enAlerte ? \'text-destructive\' : \'text-foreground\'}`}',
  'className="stk-unit"': 'className="text-[0.82rem] font-medium text-muted-foreground"',
  'className="stk-date"': 'className="text-[0.82rem] font-semibold text-muted-foreground"',
  'className="stk-val-col"': 'className="px-5 py-4 align-middle font-bold text-foreground tabular-nums"',
  'className="stk-qty-badge"': 'className="inline-block px-2.5 py-1 bg-emerald-600/10 text-emerald-700 rounded-full text-[0.82rem] font-bold"',
  'className="stk-fournisseur"': 'className="inline-flex items-center gap-1.5 text-[0.82rem] font-medium text-muted-foreground"',
  'className="stk-badge danger"': 'className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-[0.75rem] font-bold whitespace-nowrap bg-destructive/10 text-destructive"',
  'className="stk-badge success"': 'className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-[0.75rem] font-bold whitespace-nowrap bg-[#1B6B3A]/10 text-[#1B6B3A]"',
  'className="stk-empty"': 'className="flex flex-col items-center justify-center py-14 px-8 text-muted-foreground/60"',
  '<p>Aucun produit trouvé</p>': '<p className="text-[0.95rem] font-bold text-muted-foreground m-0 mt-3 mb-1">Aucun produit trouvé</p>',
  '<p>Aucune entrée de stock</p>': '<p className="text-[0.95rem] font-bold text-muted-foreground m-0 mt-3 mb-1">Aucune entrée de stock</p>',
  'className="stk-modal-overlay"': 'className="fixed inset-0 bg-slate-900/50 backdrop-blur-md flex items-center justify-center z-[1000] p-6 animate-in fade-in duration-200"',
  'className="stk-modal"': 'className="bg-gradient-to-b from-white to-slate-50 border border-border/80 rounded-[28px] w-full max-w-[500px] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300"',
  'className="stk-modal-header"': 'className="flex items-center gap-3.5 p-6 border-b border-border bg-gradient-to-b from-primary/5 to-transparent"',
  'className="stk-modal-icon"': 'className="w-11 h-11 flex items-center justify-center bg-gradient-to-br from-primary to-secondary text-white rounded-xl shadow-md shrink-0"',
  '<h3 id="stock-modal-title">Nouvelle entrée de stock</h3>': '<h3 id="stock-modal-title" className="text-[1.1rem] font-extrabold text-foreground m-0">Nouvelle entrée de stock</h3>',
  '<p>Enregistrez un réapprovisionnement</p>': '<p className="text-[0.78rem] font-medium text-muted-foreground m-0 mt-1">Enregistrez un réapprovisionnement</p>',
  'className="stk-modal-close"': 'className="w-9 h-9 flex items-center justify-center bg-muted border-none rounded-xl text-muted-foreground cursor-pointer transition-all hover:bg-muted/80 hover:text-foreground shrink-0"',
  'className="stk-modal-body"': 'className="p-6 flex flex-col gap-4"',
  'className="stk-modal-row"': 'className="grid grid-cols-1 sm:grid-cols-2 gap-3.5"',
  'className="stk-field"': 'className="flex flex-col gap-1.5"',
  '<label>': '<label className="flex items-center gap-1.5 text-[0.82rem] font-semibold text-muted-foreground">',
  '<span className="stk-req">*</span>': '<span className="text-destructive font-bold">*</span>',
  '<select': '<select className="w-full px-4 py-3 bg-slate-50 border border-border rounded-xl text-[0.88rem] font-medium text-foreground transition-all outline-none focus:border-primary focus:bg-white focus:ring-4 focus:ring-primary/10"',
  '<input\n                      type="number"': '<input\n                      type="number"\n                      className="w-full px-4 py-3 bg-slate-50 border border-border rounded-xl text-[0.88rem] font-medium text-foreground transition-all outline-none focus:border-primary focus:bg-white focus:ring-4 focus:ring-primary/10 placeholder:text-muted-foreground/60"',
  '<input\n                        type="number"': '<input\n                        type="number"\n                        className="w-full px-4 py-3 pr-14 bg-slate-50 border border-border rounded-xl text-[0.88rem] font-medium text-foreground transition-all outline-none focus:border-primary focus:bg-white focus:ring-4 focus:ring-primary/10 placeholder:text-muted-foreground/60"',
  'className="stk-input-suffix-wrap"': 'className="relative"',
  'className="stk-input-suffix"': 'className="absolute right-4 top-1/2 -translate-y-1/2 text-[0.72rem] font-bold text-muted-foreground pointer-events-none"',
  'className="stk-selected-info"': 'className="flex items-center gap-2 p-3 bg-gradient-to-b from-primary/5 to-transparent border border-primary/10 rounded-xl text-[0.82rem] font-medium text-muted-foreground"',
  'className="stk-alert-tag"': 'className="inline-flex items-center gap-1 px-2 py-0.5 bg-amber-500/10 text-amber-600 rounded-full text-[0.72rem] font-bold ml-auto"',
  'className="stk-cost-indicator"': 'className="flex items-center gap-2 p-3 bg-gradient-to-b from-[#1B6B3A]/10 to-[#1B6B3A]/5 border border-[#1B6B3A]/15 rounded-xl text-[0.82rem] font-medium text-[#1B6B3A]"',
  'className="stk-modal-footer"': 'className="flex items-center justify-end gap-2.5 p-5 border-t border-border bg-gradient-to-b from-slate-50/98 to-slate-100/90"',
  'className="stk-btn-cancel"': 'className="px-5 py-2.5 bg-white border border-border rounded-xl text-muted-foreground text-[0.85rem] font-semibold cursor-pointer transition-all hover:bg-muted hover:text-foreground"',
  'className="stk-btn-save"': 'className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-br from-[#D32F2F] to-[#b71c1c] text-white border-none rounded-xl text-[0.85rem] font-bold cursor-pointer transition-all shadow-[0_12px_26px_rgba(211,47,47,0.22)] hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-50 disabled:pointer-events-none"',
  'className="stk-spinner"': 'className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"'
};

for (const [key, value] of Object.entries(classesMap)) {
  content = content.replaceAll(key, value);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Stock JSX restructured for Tailwind successfully!');
