const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/pages/NouvelleBoutique.jsx');
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/import '\.\/NouvelleBoutique\.css';\r?\n?/, '');

const classesMap = {
  'className="nb-page"': 'className="min-h-screen bg-background font-sans"',
  'className="nb-restricted"': 'className="flex flex-col items-center justify-center min-h-[70vh] text-center p-12"',
  'className="nb-restricted-icon"': 'className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center text-primary mb-6"',
  '<h2>Plan Business requis</h2>': '<h2 className="text-2xl font-extrabold text-foreground mb-2">Plan Business requis</h2>',
  '<p>La création de boutiques est réservée au plan Business.</p>': '<p className="text-[0.95rem] text-muted-foreground mb-6">La création de boutiques est réservée au plan Business.</p>',
  'className="nb-btn-upgrade"': 'className="inline-flex items-center gap-2 px-7 py-3 bg-gradient-to-br from-[#E8623A] to-[#F4A020] text-white border-none rounded-xl text-sm font-bold cursor-pointer transition-all shadow-[0_8px_24px_rgba(211,47,47,0.3)] hover:-translate-y-0.5 hover:shadow-[0_12px_32px_rgba(211,47,47,0.4)]"',
  'className="nb-success-screen"': 'className="flex flex-col items-center justify-center min-h-[80vh] relative overflow-hidden text-center p-8"',
  'className="nb-success-bg"': 'className="absolute inset-0 pointer-events-none flex items-center justify-center"',
  'className="nb-success-ring r1"': 'className="absolute rounded-full border-2 border-emerald-500/10 w-[300px] h-[300px] animate-ping"',
  'className="nb-success-ring r2"': 'className="absolute rounded-full border-2 border-emerald-500/10 w-[450px] h-[450px] animate-pulse"',
  'className="nb-success-ring r3"': 'className="absolute rounded-full border-2 border-emerald-500/10 w-[600px] h-[600px] opacity-50"',
  'className="nb-success-content"': 'className="relative z-10 flex flex-col items-center bg-white/80 backdrop-blur-xl p-10 lg:p-14 rounded-3xl border border-white/50 shadow-xl max-w-xl mx-auto"',
  'className="nb-success-check"': 'className="w-20 h-20 rounded-full bg-emerald-500 flex items-center justify-center text-white mb-6 shadow-[0_10px_30px_rgba(16,211,153,0.3)] animate-in zoom-in spin-in-12 duration-500"',
  '<h1>Boutique créée !</h1>': '<h1 className="text-3xl font-black text-foreground mb-2">Boutique créée !</h1>',
  'className="nb-success-name"': 'className="text-xl font-bold text-muted-foreground m-0 mb-1"',
  'className="nb-success-slug"': 'className="text-sm font-mono text-emerald-600 bg-emerald-500/10 px-3 py-1 rounded-md mb-8"',
  'className="nb-success-features"': 'className="grid grid-cols-1 sm:grid-cols-2 gap-4 w-full mb-8 text-left"',
  'className="nb-sf-item"': 'className="flex items-center gap-3 p-4 bg-slate-50 border border-border rounded-xl text-[0.85rem] font-semibold text-foreground"',
  'className="nb-success-actions"': 'className="flex flex-col sm:flex-row gap-4 w-full"',
  'className="nb-btn-secondary"': 'className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-white border-2 border-border text-foreground rounded-xl font-bold hover:bg-muted transition-all"',
  'className="nb-btn-primary"': 'className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-gradient-to-br from-primary to-secondary text-white border-none rounded-xl font-bold shadow-lg shadow-primary/30 hover:-translate-y-0.5 hover:shadow-xl hover:shadow-primary/40 transition-all"',
  'className="nb-topbar"': 'className="flex items-center justify-between p-4 md:px-8 bg-white border-b border-border sticky top-0 z-50"',
  'className="nb-back-btn"': 'className="flex items-center gap-2 bg-transparent border-none text-muted-foreground text-[0.88rem] font-semibold cursor-pointer py-2 px-3 rounded-[10px] transition-all hover:bg-muted/50 hover:text-foreground"',
  'className="nb-stepper"': 'className="hidden md:flex items-center gap-10 relative"',
  'className="nb-step-track"': 'className="absolute top-1/2 left-[18px] right-[18px] h-[3px] bg-muted rounded-[3px] -translate-y-1/2 z-0"',
  'className="nb-step-fill"': 'className="h-full bg-gradient-to-r from-primary to-secondary rounded-[3px] transition-all duration-500"',
  'className={`nb-step-dot ${step >= s ? \'active\' : \'\'} ${step === s ? \'current\' : \'\'}`}': 'className={`w-8 h-8 rounded-full flex items-center justify-center text-[0.75rem] font-extrabold bg-white border-[2.5px] border-muted-foreground/30 text-muted-foreground relative z-10 transition-all duration-300 ${step >= s ? \'bg-gradient-to-br from-primary to-secondary border-primary text-white shadow-md shadow-primary/30\' : \'\'} ${step === s ? \'scale-110 shadow-lg shadow-primary/40\' : \'\'}`}',
  'className="nb-step-label"': 'className="text-[0.8rem] text-muted-foreground font-semibold"',
  'className="nb-main"': 'className="grid grid-cols-1 lg:grid-cols-[1fr_400px] min-h-[calc(100vh-65px)]"',
  'className="nb-form-side"': 'className="p-8 lg:p-12 flex flex-col"',
  'className="nb-form-container"': 'className="w-full max-w-[580px] mx-auto flex-1 flex flex-col"',
  'className={`nb-step-panel ${step === 1 ? \'active\' : step > 1 ? \'done\' : \'\'}`}': 'className={`flex flex-col animate-in slide-in-from-right-4 duration-300 ${step === 1 ? \'flex-1 block\' : \'hidden\'}`}',
  'className={`nb-step-panel ${step === 2 ? \'active\' : step > 2 ? \'done\' : \'\'}`}': 'className={`flex flex-col animate-in slide-in-from-right-4 duration-300 ${step === 2 ? \'flex-1 block\' : \'hidden\'}`}',
  'className={`nb-step-panel ${step === 3 ? \'active\' : \'\'}`}': 'className={`flex flex-col animate-in slide-in-from-right-4 duration-300 ${step === 3 ? \'flex-1 block\' : \'hidden\'}`}',
  'className="nb-step-header"': 'className="flex items-start gap-4 mb-8"',
  'className="nb-step-icon-wrap"': 'className="w-[52px] h-[52px] rounded-2xl bg-primary/10 text-primary flex items-center justify-center shrink-0"',
  'className="nb-step-icon-wrap orange"': 'className="w-[52px] h-[52px] rounded-2xl bg-[#D4880F]/10 text-[#D4880F] flex items-center justify-center shrink-0"',
  'className="nb-step-icon-wrap green"': 'className="w-[52px] h-[52px] rounded-2xl bg-emerald-600/10 text-emerald-600 flex items-center justify-center shrink-0"',
  '<h2>Identité de la boutique</h2>': '<h2 className="text-2xl font-extrabold text-foreground tracking-tight m-0 mb-1">Identité de la boutique</h2>',
  '<p>Choisissez un nom qui représente votre point de vente</p>': '<p className="text-[0.88rem] text-muted-foreground m-0 leading-relaxed">Choisissez un nom qui représente votre point de vente</p>',
  '<h2>Coordonnées</h2>': '<h2 className="text-2xl font-extrabold text-foreground tracking-tight m-0 mb-1">Coordonnées</h2>',
  '<p>Informations de contact pour cette boutique (optionnel)</p>': '<p className="text-[0.88rem] text-muted-foreground m-0 leading-relaxed">Informations de contact pour cette boutique (optionnel)</p>',
  '<h2>Récapitulatif</h2>': '<h2 className="text-2xl font-extrabold text-foreground tracking-tight m-0 mb-1">Récapitulatif</h2>',
  '<p>Vérifiez les informations avant de créer votre boutique</p>': '<p className="text-[0.88rem] text-muted-foreground m-0 leading-relaxed">Vérifiez les informations avant de créer votre boutique</p>',
  'className="nb-fields"': 'className="flex flex-col gap-6"',
  'className="nb-field"': 'className="flex flex-col gap-1.5"',
  'className="nb-field-row"': 'className="grid grid-cols-1 sm:grid-cols-2 gap-4"',
  'className="nb-label"': 'className="flex items-center gap-1.5 text-[0.82rem] font-bold text-muted-foreground tracking-wide"',
  'className="nb-required"': 'className="text-destructive font-bold flex-shrink-0"',
  'className="nb-input"': 'className="w-full px-4 py-3 bg-white border-2 border-border rounded-xl text-[0.92rem] text-foreground transition-all outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 placeholder:text-muted-foreground/50"',
  'className="nb-hint"': 'className="text-[0.75rem] text-muted-foreground font-medium mt-1"',
  'className="nb-slug-wrap"': 'className="flex items-stretch border-2 border-border rounded-xl overflow-hidden bg-white transition-all focus-within:border-primary focus-within:ring-4 focus-within:ring-primary/10"',
  'className="nb-slug-prefix"': 'className="flex items-center px-3 bg-muted text-muted-foreground text-[0.82rem] font-semibold border-r border-border whitespace-nowrap"',
  'className="nb-input nb-slug-input"': 'className="flex-1 border-none rounded-none shadow-none focus:ring-0 px-4 py-3 text-[0.92rem] text-foreground outline-none w-full"',
  'className="nb-recap"': 'className="flex flex-col gap-5"',
  'className="nb-recap-section"': 'className="bg-white border border-border rounded-[14px] p-5"',
  '<h4><FiShoppingBag size={14} /> Identité</h4>': '<h4 className="flex items-center gap-2 text-[0.82rem] font-bold text-muted-foreground uppercase tracking-widest mb-4 pb-3 border-b border-muted m-0"><FiShoppingBag size={14} /> Identité</h4>',
  '<h4><FiMapPin size={14} /> Coordonnées</h4>': '<h4 className="flex items-center gap-2 text-[0.82rem] font-bold text-muted-foreground uppercase tracking-widest mb-4 pb-3 border-b border-muted m-0"><FiMapPin size={14} /> Coordonnées</h4>',
  '<h4><FiShield size={14} /> Hérité automatiquement</h4>': '<h4 className="flex items-center gap-2 text-[0.82rem] font-bold text-muted-foreground uppercase tracking-widest mb-4 pb-3 border-b border-muted m-0"><FiShield size={14} /> Hérité automatiquement</h4>',
  'className="nb-recap-row"': 'className="flex items-center justify-between py-2 border-b border-muted/50 last:border-0"',
  'className="nb-recap-label"': 'className="text-[0.85rem] text-muted-foreground font-medium"',
  'className="nb-recap-value"': 'className="text-[0.88rem] text-foreground font-bold"',
  'className="nb-recap-value nb-slug-display"': 'className="font-mono text-[#E8623A] bg-[#E8623A]/10 px-2 py-1 rounded-md text-[0.82rem]"',
  'className="nb-recap-section nb-recap-inherit"': 'className="bg-gradient-to-br from-primary/5 to-secondary/5 border border-primary/15 rounded-[14px] p-5"',
  'className="nb-inherit-chips"': 'className="flex flex-wrap gap-2"',
  'className="nb-chip"': 'className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white border border-border rounded-full text-[0.78rem] font-semibold text-foreground"',
  'className="nb-actions"': 'className="flex items-center justify-between pt-8 mt-auto border-t border-border w-full"',
  'className="nb-actions-right"': 'className="flex gap-3 ml-auto"',
  'className="nb-btn-back"': 'className="flex items-center gap-2 px-5 py-2.5 bg-transparent border-2 border-border rounded-xl text-muted-foreground text-[0.88rem] font-semibold cursor-pointer transition-all hover:bg-muted hover:border-muted-foreground/30"',
  'className="nb-btn-next"': 'className="flex items-center gap-2 px-7 py-2.5 bg-gradient-to-br from-[#E8623A] to-[#b71c1c] text-white rounded-xl text-[0.9rem] font-bold cursor-pointer transition-all shadow-[0_6px_20px_rgba(211,47,47,0.3)] hover:-translate-y-0.5 hover:shadow-[0_10px_28px_rgba(211,47,47,0.4)] disabled:opacity-50 disabled:pointer-events-none disabled:shadow-none"',
  'className="nb-btn-create"': 'className="flex items-center gap-2 px-8 py-3 bg-gradient-to-br from-primary to-secondary text-white rounded-xl text-[0.92rem] font-bold cursor-pointer transition-all shadow-[0_6px_20px_rgba(27,94,32,0.3)] hover:-translate-y-0.5 hover:shadow-[0_10px_28px_rgba(27,94,32,0.4)] disabled:opacity-50 disabled:pointer-events-none disabled:shadow-none"',
  'className="nb-spin"': 'className="animate-spin"',
  'className="nb-preview-side"': 'className="bg-gradient-to-b from-slate-50 to-slate-100 border-l border-border p-8 overflow-y-auto hidden lg:block"',
  'className="nb-preview-sticky"': 'className="sticky top-8"',
  'className="nb-preview-label"': 'className="flex items-center gap-2 text-[0.78rem] font-bold text-muted-foreground uppercase tracking-widest mb-4"',
  'className="nb-preview-card"': 'className="relative bg-white border border-[#E8623A]/10 rounded-[20px] p-8 overflow-hidden shadow-[0_8px_32px_rgba(26,26,46,0.07)]"',
  'className="nb-preview-card-bg"': 'className="absolute inset-0 pointer-events-none overflow-hidden"',
  'className="nb-pv-orb nb-pv-orb-1"': 'className="absolute rounded-full blur-[60px] w-[200px] h-[200px] bg-[#E8623A]/10 top-[-60px] right-[-40px]"',
  'className="nb-pv-orb nb-pv-orb-2"': 'className="absolute rounded-full blur-[60px] w-[150px] h-[150px] bg-emerald-400/10 bottom-[-40px] left-[-30px]"',
  'className="nb-preview-avatar"': 'className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center text-white text-2xl font-black mx-auto mb-4 relative z-10 shadow-[0_8px_24px_rgba(27,94,32,0.25)] transition-all"',
  'className="nb-preview-name"': 'className="text-[1.15rem] font-extrabold text-foreground text-center m-0 mb-1 relative z-10 transition-all"',
  'className="nb-preview-slug"': 'className="inline-flex text-center font-mono text-[0.78rem] text-[#E8623A] bg-[#E8623A]/10 px-3 py-1 rounded-md mx-auto mb-5 relative z-10 left-1/2 -translate-x-1/2"',
  'className="nb-preview-infos"': 'className="flex flex-col gap-2 mb-5 relative z-10"',
  'className="nb-preview-info"': 'className="flex items-center gap-2 text-[0.82rem] text-muted-foreground font-medium"',
  'className="nb-preview-info nb-preview-info-empty"': 'className="flex items-center gap-2 text-[0.82rem] text-muted-foreground italic"',
  'className="nb-preview-metrics"': 'className="grid grid-cols-3 gap-2 mb-5 relative z-10"',
  'className="nb-pm-item"': 'className="flex flex-col items-center gap-1 p-3 bg-slate-50 border border-border rounded-xl"',
  '<span>0 produits</span>': '<span className="text-[0.72rem] text-muted-foreground font-semibold">0 produits</span>',
  '<span>0 clients</span>': '<span className="text-[0.72rem] text-muted-foreground font-semibold">0 clients</span>',
  '<span>0 ventes</span>': '<span className="text-[0.72rem] text-muted-foreground font-semibold">0 ventes</span>',
  'className="nb-preview-footer"': 'className="flex flex-wrap items-center justify-center gap-2 relative z-10 pt-4 border-t border-muted"',
  'className="nb-pf-badge plan"': 'className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-[0.7rem] font-bold bg-primary/10 text-primary border border-primary/20"',
  'className="nb-pf-badge network"': 'className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full text-[0.7rem] font-bold bg-emerald-500/10 text-emerald-700 border border-emerald-500/20"',
  'className="nb-tips"': 'className="mt-6 p-5 bg-white border border-border rounded-2xl"',
  '<h5><FiZap size={14} /> Conseils</h5>': '<h5 className="flex items-center gap-1.5 text-[0.82rem] font-bold text-muted-foreground m-0 mb-3"><FiZap size={14} /> Conseils</h5>',
  '<ul>': '<ul className="list-none p-0 m-0 flex flex-col gap-2">',
  '<li>Choisissez un nom court et mémorable</li>': '<li className="text-[0.78rem] text-muted-foreground font-medium pl-5 relative before:absolute before:left-0 before:top-2 before:w-1.5 before:h-1.5 before:rounded-full before:bg-primary leading-relaxed">Choisissez un nom court et mémorable</li>',
  '<li>Le slug doit être unique dans tout le système</li>': '<li className="text-[0.78rem] text-muted-foreground font-medium pl-5 relative before:absolute before:left-0 before:top-2 before:w-1.5 before:h-1.5 before:rounded-full before:bg-primary leading-relaxed">Le slug doit être unique dans tout le système</li>',
  '<li>Les coordonnées peuvent être ajoutées plus tard</li>': '<li className="text-[0.78rem] text-muted-foreground font-medium pl-5 relative before:absolute before:left-0 before:top-2 before:w-1.5 before:h-1.5 before:rounded-full before:bg-primary leading-relaxed">Les coordonnées peuvent être ajoutées plus tard</li>',
};

for (const [key, value] of Object.entries(classesMap)) {
  content = content.replaceAll(key, value);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('NouvelleBoutique JSX restructured for Tailwind successfully!');
