const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/pages/Abonnement.jsx');
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/import '\.\/Abonnement\.css';\r?\n?/, '');

const classesMap = {
  'className="abo-page"': 'className="max-w-[1180px] mx-auto p-5 md:p-8 flex flex-col gap-5 font-sans"',
  'className="abo-loading"': 'className="flex flex-col items-center justify-center gap-4 py-24 px-8 text-muted-foreground"',
  'className="abo-loading-spinner"': 'className="w-9 h-9 border-[3px] border-muted border-t-primary rounded-full animate-spin"',
  'className="abo-hero"': 'className="bg-gradient-to-br from-primary via-secondary to-accent rounded-3xl p-10 relative overflow-hidden border border-white/10 shadow-2xl before:absolute before:-top-1/2 before:-right-[20%] before:w-[400px] before:h-[400px] before:bg-[radial-gradient(circle,rgba(255,255,255,0.08)_0%,transparent_70%)] before:rounded-full after:absolute after:-bottom-[30%] after:-left-[10%] after:w-[300px] after:h-[300px] after:bg-[radial-gradient(circle,rgba(255,255,255,0.05)_0%,transparent_70%)] after:rounded-full"',
  'className="abo-hero-content"': 'className="relative z-10"',
  'className="abo-hero-badge"': 'className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-white/15 border border-white/20 rounded-full text-white/90 text-[0.78rem] font-semibold mb-4 backdrop-blur-sm"',
  '<h1>Votre abonnement</h1>': '<h1 className="text-white text-[1.75rem] font-extrabold m-0 mb-2 tracking-tight">Votre abonnement</h1>',
  '<p>Gérez votre plan, suivez votre utilisation et optimisez votre expérience TekkiPro.</p>': '<p className="text-white/80 text-[0.95rem] m-0 max-w-[500px]">Gérez votre plan, suivez votre utilisation et optimisez votre expérience TekkiPro.</p>',
  'className="abo-status-section"': 'className="bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-3xl overflow-hidden shadow-md"',
  'className="abo-status-main"': 'className="flex flex-col md:flex-row md:items-center justify-between p-7 md:p-8 gap-6"',
  'className="abo-status-plan"': 'className="flex items-center gap-5"',
  'className={`abo-plan-icon-lg plan-icon-${data.plan.toLowerCase()}`}' : 'className={`w-[60px] h-[60px] rounded-2xl flex items-center justify-center shrink-0 ${data.plan === \'GRATUIT\' ? \'bg-muted text-muted-foreground\' : data.plan === \'PRO\' ? \'bg-[#1B6B3A]/10 text-[#1B6B3A]\' : \'bg-amber-500/10 text-amber-500\'}`}',
  'className="abo-status-info"': 'className="flex flex-col gap-1"',
  'className="abo-status-label"': 'className="text-[0.78rem] font-semibold text-muted-foreground uppercase tracking-widest"',
  'className="abo-status-plan-name"': 'className="text-2xl font-extrabold text-foreground m-0 leading-tight"',
  'className="abo-status-meta"': 'className="flex items-center gap-3 mt-1"',
  'className="abo-meta-item"': 'className="flex items-center gap-1.5 text-[0.82rem] text-muted-foreground"',
  'className={`abo-days-pill ${daysRemaining <= 7 ? \'urgent\' : daysRemaining <= 15 ? \'warning\' : \'\'}`}' : 'className={`px-3 py-1 rounded-full text-[0.75rem] font-bold ${daysRemaining <= 7 ? \'bg-red-50 text-red-600 animate-pulse\' : daysRemaining <= 15 ? \'bg-amber-50 text-amber-700\' : \'bg-emerald-50 text-emerald-700\'}`}',
  'className="abo-status-free"': 'className="text-[0.85rem] text-muted-foreground"',
  'className="abo-status-actions"': 'className="shrink-0"',
  'className="abo-renew-btn"': 'className="inline-flex items-center gap-2 px-6 py-2.5 bg-primary text-white border-none rounded-xl text-[0.88rem] font-bold cursor-pointer transition-all hover:bg-primary/90 hover:-translate-y-0.5 hover:shadow-lg"',
  'className="abo-usage-grid"': 'className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 border-t border-border/50 bg-gradient-to-b from-slate-50/60 to-transparent"',
  'className="abo-usage-card"': 'className="p-6 relative border-b sm:border-b-0 sm:border-r border-border/50 last:border-0"',
  'className="abo-usage-card-header"': 'className="flex items-center justify-between mb-2"',
  'className="abo-usage-icon users"': 'className="w-10 h-10 rounded-xl flex items-center justify-center bg-primary/10 text-primary"',
  'className="abo-usage-icon products"': 'className="w-10 h-10 rounded-xl flex items-center justify-center bg-amber-500/10 text-amber-500"',
  'className="abo-usage-icon clients"': 'className="w-10 h-10 rounded-xl flex items-center justify-center bg-destructive/10 text-destructive"',
  'className="abo-usage-icon sales"': 'className="w-10 h-10 rounded-xl flex items-center justify-center bg-primary/10 text-primary"',
  'className="abo-usage-icon categories"': 'className="w-10 h-10 rounded-xl flex items-center justify-center bg-[#D4880F]/10 text-[#D4880F]"',
  'className="abo-usage-values"': 'className="flex items-baseline gap-1"',
  'className="abo-usage-current"': 'className="text-2xl font-extrabold text-foreground"',
  'className="abo-usage-sep"': 'className="text-base text-muted-foreground/60 mx-0.5"',
  'className="abo-usage-limit"': 'className="text-base text-muted-foreground font-semibold"',
  'className="abo-usage-label"': 'className="text-[0.82rem] text-muted-foreground mb-3"',
  'className="abo-usage-track"': 'className="h-2 bg-gradient-to-b from-slate-100 to-slate-200 rounded-full overflow-hidden mb-2"',
  'className="abo-usage-fill users"': 'className="h-full rounded-full transition-all duration-700 bg-gradient-to-r from-primary to-secondary"',
  'className="abo-usage-fill products"': 'className="h-full rounded-full transition-all duration-700 bg-gradient-to-r from-amber-500 to-amber-400"',
  'className="abo-usage-fill clients"': 'className="h-full rounded-full transition-all duration-700 bg-gradient-to-r from-destructive to-red-600"',
  'className="abo-usage-fill sales"': 'className="h-full rounded-full transition-all duration-700 bg-gradient-to-r from-primary to-secondary"',
  'className="abo-usage-fill categories"': 'className="h-full rounded-full transition-all duration-700 bg-gradient-to-r from-[#D4880F] to-secondary"',
  'className="abo-usage-pct"': 'className="inline-flex items-center px-2 py-1 rounded-full text-[0.75rem] text-muted-foreground font-semibold bg-slate-400/10"',
  'className="abo-plans-section"': 'className="mt-0"',
  'className="abo-plans-header"': 'className="mb-5 p-6 bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-[22px] shadow-sm"',
  '<h3>Choisissez votre plan</h3>': '<h3 className="text-xl font-extrabold text-foreground m-0 mb-1">Choisissez votre plan</h3>',
  '<p>Sélectionnez le plan qui correspond le mieux à votre activité.</p>': '<p className="text-[0.9rem] text-muted-foreground m-0">Sélectionnez le plan qui correspond le mieux à votre activité.</p>',
  'className="abo-plans-grid"': 'className="grid grid-cols-1 lg:grid-cols-3 gap-5 items-stretch"',
  'className={`abo-plan-card ${p.popular ? \'popular\' : \'\'} ${isCurrent ? \'current\' : \'\'}`}' : 'className={`bg-gradient-to-b from-white/98 to-slate-50/96 border-[1.5px] rounded-3xl flex flex-col relative transition-all duration-300 overflow-hidden backdrop-blur-md hover:-translate-y-1.5 hover:shadow-xl before:absolute before:inset-x-0 before:top-0 before:h-[3px] before:bg-gradient-to-r before:from-primary before:to-secondary before:opacity-85 ${p.popular ? \'border-primary shadow-[0_8px_30px_rgba(27,94,32,0.12)]\' : isCurrent ? \'border-[#1B6B3A] shadow-sm\' : \'border-border/80 shadow-sm\'}`}',
  'className="abo-popular-ribbon"': 'className="absolute top-0 inset-x-0 text-center p-1.5 text-[0.72rem] font-extrabold uppercase tracking-widest bg-gradient-to-r from-primary to-secondary text-white"',
  'className="abo-current-ribbon"': 'className="absolute top-0 inset-x-0 text-center p-1.5 text-[0.72rem] font-extrabold uppercase tracking-widest bg-gradient-to-r from-primary to-secondary text-white"',
  'className="abo-plan-card-top"': 'className="p-9 pb-6 text-center pt-8"',
  'className="abo-plan-icon-wrap"': 'className="w-[52px] h-[52px] rounded-2xl inline-flex items-center justify-center mb-4"',
  'className="abo-plan-name"': 'className="text-xl font-extrabold text-foreground m-0 mb-1"',
  'className="abo-plan-desc"': 'className="text-[0.82rem] text-muted-foreground m-0 mb-5"',
  'className="abo-plan-pricing"': 'className="flex flex-col items-center gap-0.5"',
  'className="abo-plan-amount"': 'className="text-4xl font-extrabold text-foreground leading-none tracking-tight"',
  'className="abo-plan-period"': 'className="text-[0.82rem] text-muted-foreground font-medium"',
  'className="abo-plan-divider"': 'className="h-[1px] bg-border/80 mx-7"',
  'className="abo-plan-features"': 'className="list-none p-6 mx-0 flex-1 flex flex-col gap-0"',
  '<li>': '<li className="flex items-center gap-2.5 py-2 text-[0.86rem] text-muted-foreground/90">',
  'className="abo-feature-check"': 'className="w-5 h-5 rounded-full flex items-center justify-center shrink-0 bg-current text-white"',
  'className="abo-feature-locked"': 'className="flex items-center gap-2.5 py-2 text-[0.86rem] text-muted-foreground/60 opacity-75"',
  'className="abo-feature-lock"': 'className="w-5 h-5 rounded-full flex items-center justify-center bg-muted text-muted-foreground/80 shrink-0"',
  'className="abo-plan-card-bottom"': 'className="px-6 pb-6"',
  'className={`abo-plan-cta ${p.popular ? \'primary\' : \'outline\'}`}' : 'className={`flex items-center justify-center gap-2 w-full py-3 px-5 rounded-xl text-[0.9rem] font-bold cursor-pointer transition-all shadow-sm hover:-translate-y-0.5 ${p.popular ? \'border-none bg-primary text-white hover:bg-accent\' : \'border-[1.5px] border-border bg-transparent text-foreground hover:border-primary hover:text-primary hover:bg-primary/5\'}`}',
  'className="abo-plan-cta downgrade"': 'className="flex items-center justify-center gap-2 w-full py-3 px-5 rounded-xl text-[0.9rem] font-bold cursor-pointer transition-all border-[1.5px] border-border bg-transparent text-muted-foreground shadow-sm hover:border-destructive hover:text-destructive hover:bg-destructive/10 hover:-translate-y-0.5"',
  'className="abo-plan-cta current-btn"': 'className="flex items-center justify-center gap-2 w-full py-3 px-5 rounded-xl text-[0.9rem] font-bold cursor-pointer transition-all border-[1.5px] border-[#a7f3d0] bg-emerald-50 text-[#155230] shadow-sm hover:bg-emerald-100/80 hover:-translate-y-0.5"',
  'className="abo-plan-current-label"': 'className="flex items-center justify-center gap-1.5 p-3 text-[#155230] text-[0.88rem] font-semibold rounded-xl bg-emerald-600/10 border border-emerald-600/15"',
  'className="abo-history-section"': 'className="bg-gradient-to-b from-white/98 to-slate-50/96 border border-border/80 rounded-3xl overflow-hidden shadow-sm backdrop-blur-md mt-6"',
  'className="abo-history-header"': 'className="padding-6 border-b border-border/60 p-6"',
  '<h3><FiClock size={18} /> Historique des paiements</h3>': '<h3 className="flex items-center gap-2 text-[1.05rem] font-bold text-foreground m-0"><FiClock size={18} /> Historique des paiements</h3>',
  'className="abo-history-table-wrap"': 'className="overflow-x-auto"',
  'className="abo-history-table"': 'className="w-full border-collapse text-left"',
  '<thead>\n                <tr>': '<thead className="bg-slate-50 border-b border-border">\n                <tr>',
  '<th scope="col">Plan</th>': '<th scope="col" className="px-4 py-3 text-[0.75rem] font-bold text-muted-foreground uppercase tracking-widest">Plan</th>',
  '<th scope="col">Montant</th>': '<th scope="col" className="px-4 py-3 text-[0.75rem] font-bold text-muted-foreground uppercase tracking-widest">Montant</th>',
  '<th scope="col">Période</th>': '<th scope="col" className="px-4 py-3 text-[0.75rem] font-bold text-muted-foreground uppercase tracking-widest">Période</th>',
  '<th scope="col">Statut</th>': '<th scope="col" className="px-4 py-3 text-[0.75rem] font-bold text-muted-foreground uppercase tracking-widest">Statut</th>',
  '<th scope="col">Paiement</th>': '<th scope="col" className="px-4 py-3 text-[0.75rem] font-bold text-muted-foreground uppercase tracking-widest">Paiement</th>',
  '<tr key={abo.id}>': '<tr key={abo.id} className="hover:bg-slate-50/50 transition-colors border-b border-slate-50 last:border-0">',
  '<th scope="row">': '<th scope="row" className="px-4 py-3.5 font-normal">',
  '<td>': '<td className="px-4 py-3.5">',
  'className="abo-hist-plan"': 'className="flex items-center gap-2"',
  'className={`abo-hist-dot dot-${abo.plan.toLowerCase()}`}' : 'className={`w-2 h-2 rounded-full shrink-0 ${abo.plan === \'GRATUIT\' ? \'bg-muted-foreground\' : abo.plan === \'PRO\' ? \'bg-primary\' : \'bg-secondary\'}`}',
  '<strong>{abo.plan}</strong>': '<strong className="font-[600] text-[0.88rem] text-foreground">{abo.plan}</strong>',
  'className="abo-hist-amount"': 'className="px-4 py-3.5 font-bold text-[0.88rem] text-foreground tabular-nums"',
  'className="abo-hist-dates"': 'className="flex items-center gap-1.5 text-[0.82rem] text-muted-foreground"',
  'className={`abo-hist-status status-${abo.statut.toLowerCase()}`}' : 'className={`inline-flex px-3 py-1 rounded-full text-[0.72rem] font-bold uppercase tracking-wide ${abo.statut === \'ACTIF\' ? \'bg-emerald-50 text-emerald-700\' : abo.statut === \'EXPIRE\' ? \'bg-amber-50 text-amber-700\' : \'bg-red-50 text-red-600\'}`}',
  'className="abo-hist-payment"': 'className="flex items-center gap-1.5 text-[0.82rem] text-muted-foreground"',
  'className="abo-hist-ref"': 'className="px-2 py-0.5 bg-muted rounded text-[0.75rem] font-mono text-muted-foreground"',
  'className="abo-modal-overlay"': 'className="fixed inset-0 bg-slate-900/56 backdrop-blur-md flex items-center justify-center z-[1000] p-4 animate-in fade-in duration-200"',
  'className="abo-modal"': 'className="bg-gradient-to-b from-white/99 to-slate-50/98 border border-border/80 rounded-[28px] w-full max-w-[490px] max-h-[90vh] overflow-y-auto relative shadow-[0_28px_80px_rgba(15,23,42,0.24)] animate-in zoom-in-95 duration-300"',
  'className="abo-modal-close"': 'className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center bg-transparent border-none rounded-full text-muted-foreground hover:bg-muted cursor-pointer transition-colors z-10"',
  'className="abo-modal-header"': 'className="flex flex-col items-center pt-8 pb-6 px-6 relative"',
  'className="abo-modal-icon"': 'className="w-14 h-14 rounded-2xl flex items-center justify-center bg-gradient-to-br from-primary to-secondary text-white shadow-md mb-4"',
  '<h3 id="abonnement-modal-title">': '<h3 id="abonnement-modal-title" className="text-xl font-extrabold text-foreground m-0 mb-1.5 text-center">',
  'className="abo-modal-price"': 'className="text-2xl font-extrabold text-foreground tracking-tight flex items-baseline gap-1"',
  '<span>/ mois</span>': '<span className="text-[0.85rem] font-medium text-muted-foreground">/ mois</span>',
  'className="abo-modal-body"': 'className="px-6 pb-2 space-y-5"',
  'className="abo-modal-field"': 'className="flex flex-col gap-2"',
  'className="abo-modal-label"': 'className="text-[0.82rem] font-bold text-foreground flex items-center gap-1.5"',
  'className="abo-pay-grid"': 'className="grid grid-cols-2 gap-2.5"',
  'className={`abo-pay-option ${paiement.modePaiement === key ? \'selected\' : \'\'}`}' : 'className={`flex items-center gap-2 p-3 rounded-xl border-2 text-[0.85rem] font-bold cursor-pointer transition-all ${paiement.modePaiement === key ? \'border-primary bg-primary/5 text-primary shadow-sm\' : \'border-transparent bg-white shadow-sm text-muted-foreground hover:bg-slate-50 hover:text-foreground\'}`}',
  'className="abo-pay-emoji"': 'className="text-lg shrink-0"',
  'className="abo-pay-name"': 'className="flex-1 text-left"',
  'className="abo-pay-check"': 'className="shrink-0 text-primary"',
  'className="abo-modal-help"': 'className="text-[0.82rem] text-muted-foreground mt-1"',
  'className="abo-modal-input"': 'className="w-full px-4 py-3 bg-white border border-border rounded-xl text-[0.88rem] font-medium text-foreground transition-all outline-none focus:border-primary focus:ring-4 focus:ring-primary/10 placeholder:text-muted-foreground"',
  '<span className="optional">(optionnel)</span>': '<span className="font-normal text-muted-foreground">(optionnel)</span>',
  'className="abo-modal-footer"': 'className="p-6 pt-4 flex flex-col gap-2.5"',
  'className="abo-modal-confirm"': 'className="flex items-center justify-center gap-2 w-full py-3.5 bg-gradient-to-br from-primary to-secondary text-white border-none rounded-xl text-[0.95rem] font-bold cursor-pointer transition-all shadow-[0_8px_20px_rgba(27,94,32,0.2)] hover:-translate-y-0.5 hover:shadow-lg disabled:opacity-50 disabled:pointer-events-none"',
  'className="abo-btn-spinner"': 'className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"',
  'className="abo-modal-cancel"': 'className="w-full py-3 bg-transparent border-none text-muted-foreground font-bold cursor-pointer text-[0.9rem] hover:text-foreground"'
};

for (const [key, value] of Object.entries(classesMap)) {
  content = content.replaceAll(key, value);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log('Abonnement JSX restructured for Tailwind successfully!');
