export const TP = {
  bg: '#F5F2ED',
  card: '#FFFFFF',
  border: '#E8E2D9',
  text: '#1A1A18',
  muted: '#6B7280',
  primary: '#1B5E20',       // Vert Baobab
  primaryLight: 'rgba(27, 94, 32, 0.10)',
  primaryDark: '#154d19',
  secondary: '#FFD600',     // Or du Sénégal
  secondaryLight: 'rgba(255, 214, 0, 0.12)',
  secondaryDark: '#F9A825',
  accent: '#D32F2F',        // Rouge Gorée
  accentLight: 'rgba(211, 47, 47, 0.10)',
  success: '#1B5E20',
  successLight: '#e8f5e9',
  error: '#EF4444',
  errorLight: 'rgba(239, 68, 68, 0.10)',
  textPrimary: '#1A1A18',
  textSecondary: '#475569',
  textMuted: '#6B7280',
};

export const DARK_THEME = {
  background: '#071C08',
  headerBg: '#0D2710',
  cardBg: '#0F2212',
  cardBorder: 'rgba(255, 214, 0, 0.10)',
  surfaceBg: 'rgba(27, 94, 32, 0.12)',
  surfaceBorder: 'rgba(27, 94, 32, 0.25)',
  accentBg: 'rgba(255, 214, 0, 0.15)',
  accentText: '#FFD600',
  text: '#F5F0E8',
  muted: '#9CA3AF',
  faint: '#6B7280',
  warningBg: '#1A1800',
  warningBorder: '#3D3300',
  dangerBg: '#1A0A08',
  dangerBorder: '#450A0A',
  overlay: 'rgba(7, 28, 8, 0.85)',
};

export const STATUT_COLORS = {
  COMPLETEE: '#1B6B3A',
  EN_CREDIT: '#F4A020',
  ANNULEE: '#EF4444',
};

export const ICON_COLORS = [TP.primary, TP.secondary, TP.accent];

export const SALES_TEXT = {
  fr: {
    statusLabels: { COMPLETEE: 'Complétée', EN_CREDIT: 'À crédit', ANNULEE: 'Annulée' },
    paymentLabels: { CASH: 'Cash', MOBILE_MONEY: 'MoMo', CREDIT: 'Crédit' },
    walkInClient: 'Client', seller: 'Vendeur', payment: 'Paiement', dash: '—', itemsCount: (count) => `${count} article(s)`, viewTicket: 'Voir ticket',
    error: 'Erreur', validation: 'Validation', clientNameRequired: 'Le nom du client est obligatoire.', success: 'Succès', clientCreatedSelected: 'Client ajouté et sélectionné pour cette vente.', clientCreateError: "Impossible d'ajouter ce client.",
    lowStockTitle: 'Stock insuffisant', limitedStockTitle: 'Stock limité', clientRequired: 'Client requis', creditClientRequired: 'Sélectionnez un client pour enregistrer une vente à crédit.', invalidAmountTitle: 'Montant invalide', invalidAmountMin: 'Le montant payé doit être supérieur ou égal à 0.', invalidAmountMax: 'Le montant payé ne peut pas dépasser le total du panier.',
    saleSavedTitle: 'Vente enregistrée', close: 'Fermer', openTicket: 'Voir ticket', viewPlans: 'Voir les abonnements', saleSaveError: 'Impossible de valider la vente.',
    salesDashboard: 'Pilotage des ventes', totalSales: 'Total ventes', completed: 'Complétées', onCredit: 'À crédit', revenue: 'Chiffre', totalCart: 'Total panier', transactionsCount: (count) => `${count} vente(s)`, foundProducts: (count) => `${count} produit(s) trouvé(s)`, showingFirst: (count) => `Affichage des ${count} premiers`, noClientFound: 'Aucun client trouvé pour cette recherche.', loadingClients: 'Chargement des clients...',
    quickSaleBadge: 'Vente rapide', quickSaleTitle: 'Encaisser une vente', quickSaleSubtitle: 'Ajoutez des produits, choisissez un client si besoin puis validez.', scanProducts: 'Scanner', manualSaleTitle: 'Vente au catalogue', manualSaleText: 'Choisissez les produits et quantités à vendre directement depuis le stock.',
    searchProduct: 'Rechercher un produit à vendre...', catalogLoading: 'Chargement du catalogue...', emptyCatalogTitle: "Aucun produit disponible", emptyCatalogText: "Ajoutez d'abord des produits dans le stock pour commencer à vendre.", codeOk: "Code OK", noCode: 'Sans code', addBaseUnit: (unit) => `1 ${unit || 'u'}`,
    cartEmptyTitle: 'Panier vide', cartEmptyText: 'Ajoutez des produits depuis le catalogue ou avec le scanner pour commencer la vente.', cartSectionTitle: 'Produits scannés / panier', cartSectionHint: 'Les produits ajoutés apparaissent ici avant validation.', remove: 'Retirer',
    customerForCredit: 'Client pour la vente', addCustomer: 'Nouveau client', walkIn: 'Passage', walkInSelected: 'Client de passage sélectionné.', selectedCustomer: 'Client sélectionné', change: 'Changer', phoneMissing: 'Téléphone non renseigné', debtTotal: (value) => `Dette actuelle : ${value}`,
    clientHelper: 'Un client est recommandé pour les ventes à crédit et le suivi fidélité.', searchClient: 'Rechercher un client par nom ou téléphone...', noPhone: 'Sans téléphone', chooseNoClient: 'Continuer sans client',
    creditSale: 'Vente à crédit', creditHint: 'Le montant payé maintenant est optionnel. Le reste sera enregistré comme dette client.', amountPaidNow: 'Montant payé maintenant', paidNow: (value) => `Payé maintenant : ${value}`, remainingToPay: (value) => `Reste à payer : ${value}`, zeroPaymentWarning: 'Aucun montant payé : la vente sera entièrement enregistrée en dette.',
    validateSale: 'Valider la vente', validating: 'Validation…',
    searchSale: 'Rechercher une vente, un client ou un produit...', filters: { TOUTES: 'Toutes', COMPLETEE: 'Complétées', EN_CREDIT: 'Crédit', ANNULEE: 'Annulées' }, historyTitle: 'Historique des ventes',
    noSale: 'Aucune vente trouvée',
    modalTitle: 'Nouveau client', modalSubtitle: 'Ajoutez un client et attachez-le immédiatement à cette vente.', name: 'Nom', firstName: 'Prénom', phone: 'Téléphone', address: 'Adresse', addressPlaceholder: 'Adresse / quartier', cancel: 'Annuler', creating: 'Création...', createClient: 'Créer le client',
    productLine: (produit, stock, price, locale) => `${produit} • Stock ${stock} • ${(price || 0).toLocaleString(locale)} FCFA`,
    expirationSoonTitle: 'Péremption proche',
    expiredProductTitle: 'Produit expiré',
    expirationSoonMessage: (name, date, days) => `${name} expire le ${date}${Number.isFinite(days) ? ` (dans ${days} j)` : ''}. Vérifiez avant de vendre.`,
    expiredProductMessage: (name, date, days) => `${name} est expiré depuis ${days} j (${date}). Vérifiez avant de vendre.`,
    expirationSoonBadge: (date, days) => `Expire le ${date}${Number.isFinite(days) ? ` • ${days} j` : ''}`,
    expiredProductBadge: (date, days) => `Expiré • ${days} j (${date})`,
    tabHistory: 'Historique',
    tabNewSale: 'Nouvelle Vente',
    periodToday: "Aujourd'hui",
    periodWeek: 'Semaine',
    periodMonth: 'Mois',
    totalPeriod: 'Total',
    transactions: 'Transactions',
    trendBadge: '+12%',
  },
  en: {
    statusLabels: { COMPLETEE: 'Completed', EN_CREDIT: 'On credit', ANNULEE: 'Cancelled' },
    paymentLabels: { CASH: 'Cash', MOBILE_MONEY: 'MoMo', CREDIT: 'Credit' },
    walkInClient: 'Customer', seller: 'Seller', payment: 'Payment', dash: '—', itemsCount: (count) => `${count} item(s)`, viewTicket: 'View receipt',
    error: 'Error', validation: 'Validation', clientNameRequired: 'Client name is required.', success: 'Success', clientCreatedSelected: 'Client added and selected for this sale.', clientCreateError: 'Unable to add this client.',
    lowStockTitle: 'Insufficient stock', limitedStockTitle: 'Limited stock', clientRequired: 'Client required', creditClientRequired: 'Select a client to save a credit sale.', invalidAmountTitle: 'Invalid amount', invalidAmountMin: 'Amount paid must be greater than or equal to 0.', invalidAmountMax: 'Amount paid cannot exceed cart total.',
    saleSavedTitle: 'Sale saved', close: 'Close', openTicket: 'View receipt', viewPlans: 'View plans', saleSaveError: 'Unable to validate the sale.',
    salesDashboard: 'Sales dashboard', totalSales: 'Total sales', completed: 'Completed', onCredit: 'On credit', revenue: 'Revenue', totalCart: 'Cart total', transactionsCount: (count) => `${count} sale(s)`, foundProducts: (count) => `${count} product(s) found`, showingFirst: (count) => `Showing first ${count}`, noClientFound: 'No client found for this search.', loadingClients: 'Loading clients...',
    quickSaleBadge: 'Quick sale', quickSaleTitle: 'Process a sale', quickSaleSubtitle: 'Add products, choose a client if needed, then validate.', scanProducts: 'Scan', manualSaleTitle: 'Catalog sale', manualSaleText: 'Choose products and quantities to sell directly from stock.',
    searchProduct: 'Search for a product to sell...', catalogLoading: 'Loading catalog...', emptyCatalogTitle: 'No product available', emptyCatalogText: 'Add products to stock first to start selling.', codeOk: 'Code OK', noCode: 'No code', addBaseUnit: (unit) => `1 ${unit || 'u'}`,
    cartEmptyTitle: 'Empty cart', cartEmptyText: 'Add products from the catalog or scanner to start the sale.', cartSectionTitle: 'Scanned products / cart', cartSectionHint: 'Products added for the sale appear here before validation.', remove: 'Remove',
    customerForCredit: 'Customer for sale', addCustomer: 'New client', walkIn: 'Walk-in', walkInSelected: 'Walk-in customer selected.', selectedCustomer: 'Selected client', change: 'Change', phoneMissing: 'Phone not provided', debtTotal: (value) => `Current debt: ${value}`,
    clientHelper: 'A client is recommended for credit sales and loyalty tracking.', searchClient: 'Search by client name or phone...', noPhone: 'No phone', chooseNoClient: 'Continue without client',
    creditSale: 'Credit sale', creditHint: 'Amount paid now is optional. The remaining balance will be recorded as customer debt.', amountPaidNow: 'Amount paid now', paidNow: (value) => `Paid now: ${value}`, remainingToPay: (value) => `Remaining to pay: ${value}`, zeroPaymentWarning: 'No amount paid: the sale will be fully recorded as debt.',
    validateSale: 'Validate sale', validating: 'Validating…',
    searchSale: 'Search for a sale, client or product...', filters: { TOUTES: 'All', COMPLETEE: 'Completed', EN_CREDIT: 'Credit', ANNULEE: 'Cancelled' }, historyTitle: 'Sales history',
    noSale: 'No sale found',
    modalTitle: 'New client', modalSubtitle: 'Add a client and attach them to this sale immediately.', name: 'Name', firstName: 'First name', phone: 'Phone', address: 'Address', addressPlaceholder: 'Address / area', cancel: 'Cancel', creating: 'Creating...', createClient: 'Create client',
    productLine: (produit, stock, price, locale) => `${produit} • Stock ${stock} • ${(price || 0).toLocaleString(locale)} FCFA`,
    expirationSoonTitle: 'Expiration soon',
    expiredProductTitle: 'Expired product',
    expirationSoonMessage: (name, date, days) => `${name} expires on ${date}${Number.isFinite(days) ? ` (in ${days} d)` : ''}. Check it before selling.`,
    expiredProductMessage: (name, date, days) => `${name} expired ${days} d ago (${date}). Check it before selling.`,
    expirationSoonBadge: (date, days) => `Expires on ${date}${Number.isFinite(days) ? ` • ${days} d` : ''}`,
    expiredProductBadge: (date, days) => `Expired • ${days} d (${date})`,
    tabHistory: 'History',
    tabNewSale: 'New Sale',
    periodToday: 'Today',
    periodWeek: 'Week',
    periodMonth: 'Month',
    totalPeriod: 'Total',
    transactions: 'Transactions',
    trendBadge: '+12%',
  },
};

export const MAX_VISIBLE_PRODUCTS = 12;
export const MAX_VISIBLE_CLIENTS = 6;
export const EMPTY_CLIENT_FORM = { nom: '', prenom: '', telephone: '', adresse: '' };
export const DAY_IN_MS = 24 * 60 * 60 * 1000;
