export const DARK_THEME = {
  background:    '#071C08',
  headerBg:      '#0D2710',
  cardBg:        '#0F2212',
  cardBorder:    'rgba(255,214,0,0.10)',
  surfaceBg:     'rgba(27,94,32,0.12)',
  surfaceBorder: 'rgba(27,94,32,0.25)',
  accentBg:      'rgba(255,214,0,0.15)',
  accentText:    '#FFD600',
  text:          '#F5F0E8',
  muted:         '#9CA3AF',
  faint:         '#6B7280',
  overlay:       'rgba(7,28,8,0.80)',
};

export const UNITES_BASE = [
  { value: 'g', label: 'Gramme (g)' },
  { value: 'ml', label: 'Millilitre (ml)' },
  { value: 'piece', label: 'Pièce' },
  { value: 'paquet', label: 'Paquet' },
  { value: 'm', label: 'Mètre (m)' },
];

export const COMMERCIAL_FLOWS = {
  poids: {
    title: 'Produit vendu par sac / poids',
    description: 'Riz, sucre, farine, céréales…',
    uniteBase: 'g',
    packLabel: 'Sac',
    packLabelPlural: 'sacs',
    sizeLabel: "Poids d'un sac",
    sizeUnit: 'kg',
    countLabel: 'Nombre de sacs en stock',
    alertLabel: "Seuil d'alerte (en sacs)",
    purchaseLabel: "Prix d'achat par sac",
    saleLabel: 'Prix de vente par sac',
    sizePlaceholder: 'Ex: 50',
    countPlaceholder: 'Ex: 10',
    detailUnits: ['1 kg', '500 g', '250 g'],
  },
  volume: {
    title: 'Produit vendu par bidon / volume',
    description: 'Huile, lait, eau, jus…',
    uniteBase: 'ml',
    packLabel: 'Bidon',
    packLabelPlural: 'bidons',
    sizeLabel: "Volume d'un bidon",
    sizeUnit: 'L',
    countLabel: 'Nombre de bidons en stock',
    alertLabel: "Seuil d'alerte (en bidons)",
    purchaseLabel: "Prix d'achat par bidon",
    saleLabel: 'Prix de vente par bidon',
    sizePlaceholder: 'Ex: 20',
    countPlaceholder: 'Ex: 8',
    detailUnits: ['1 L', '1/2 L', '1/4 L', '1/8 L'],
  },
  carton: {
    title: 'Produit vendu par carton',
    description: 'Spaghetti, biscuits, paquets…',
    uniteBase: 'piece',
    packLabel: 'Carton',
    packLabelPlural: 'cartons',
    sizeLabel: 'Unités dans un carton',
    sizeUnit: 'unités',
    countLabel: 'Nombre de cartons en stock',
    alertLabel: "Seuil d'alerte (en cartons)",
    purchaseLabel: "Prix d'achat par carton",
    saleLabel: 'Prix de vente par carton',
    sizePlaceholder: 'Ex: 40',
    countPlaceholder: 'Ex: 12',
    detailUnits: ['Unité'],
  },
};

export const SUGGESTIONS_UNITES = {
  g: [
    { nom: 'Sac 50kg', facteur: 50000 },
    { nom: 'Sac 25kg', facteur: 25000 },
    { nom: 'Kilogramme', facteur: 1000 },
    { nom: '500 grammes', facteur: 500 },
    { nom: '250 grammes', facteur: 250 },
  ],
  ml: [
    { nom: 'Bidon 20L', facteur: 20000 },
    { nom: 'Bidon 5L', facteur: 5000 },
    { nom: 'Litre', facteur: 1000 },
    { nom: '1/2 litre', facteur: 500 },
    { nom: '1/4 litre', facteur: 250 },
  ],
  piece: [
    { nom: 'Carton 12 unités', facteur: 12 },
    { nom: 'Carton 24 unités', facteur: 24 },
    { nom: 'Paquet de 6', facteur: 6 },
  ],
  paquet: [
    { nom: 'Carton 12 paquets', facteur: 12 },
    { nom: 'Lot de 6 paquets', facteur: 6 },
  ],
  m: [
    { nom: 'Rouleau 25m', facteur: 25 },
    { nom: 'Rouleau 50m', facteur: 50 },
  ],
};

export const FORM_TEXT = {
  fr: {
    unitLabels: { g: 'Gramme (g)', ml: 'Millilitre (ml)', piece: 'Pièce', paquet: 'Paquet', m: 'Mètre (m)' },
    flowTexts: {
      poids: { title: "Produit vendu par sac / poids", description: "Riz, sucre, farine, céréales…", packLabel: "Sac", packLabelPlural: "sacs", sizeLabel: "Poids d'un sac", countLabel: "Nombre de sacs en stock", alertLabel: "Seuil d'alerte (en sacs)", saleLabel: "Prix de vente du sac", purchaseLabel: "Prix d'achat du sac" },
      volume: { title: "Produit vendu par bidon / volume", description: "Huile, lait, eau, jus…", packLabel: "Bidon", packLabelPlural: "bidons", sizeLabel: "Volume d'un bidon", countLabel: "Nombre de bidons en stock", alertLabel: "Seuil d'alerte (en bidons)", saleLabel: "Prix de vente du bidon", purchaseLabel: "Prix d'achat du bidon" },
      carton: { title: "Produit vendu par carton", description: "Spaghetti, biscuits, paquets…", packLabel: "Carton", packLabelPlural: "cartons", sizeLabel: "Unités dans un carton", countLabel: "Nombre de cartons en stock", alertLabel: "Seuil d'alerte (en cartons)", saleLabel: "Prix de vente du carton", purchaseLabel: "Prix d'achat du carton" },
    },
    error: 'Erreur', editTitle: 'Modifier le produit', createTitle: 'Nouveau produit', loadTitle: 'Chargement impossible', loadError: 'Impossible de charger le produit.', back: 'Retour',
    cameraPermissionTitle: 'Permission caméra', cameraPermissionText: 'Autorisez la caméra pour scanner le code-barres du produit.',
    accessDenied: 'Accès refusé', adminOnly: (isEditing) => `Seul un administrateur peut ${isEditing ? 'modifier' : 'créer'} un produit.`, requiredField: 'Champ requis',
    requiredName: 'Veuillez saisir le nom du produit.', requiredBarcode: 'Veuillez saisir ou scanner un code-barres.', requiredSize: 'Veuillez saisir la taille du conditionnement.', requiredPackSale: 'Veuillez saisir le prix de vente du conditionnement.', requiredPackPurchase: "Veuillez saisir le prix d'achat du conditionnement.", requiredSale: 'Veuillez saisir le prix de vente.',
    updatedTitle: 'Produit mis à jour', createdTitle: 'Produit créé', updatedMessage: (name) => `${name} a été modifié avec succès.`, createdMessage: (name) => `${name} a été enregistré avec succès.`, backToStock: 'Retour au stock', createAnother: 'Créer un autre', viewStock: 'Voir le stock', viewPlans: 'Voir les abonnements', saveError: (isEditing) => `Impossible de ${isEditing ? 'modifier' : 'créer'} le produit.`,
    adminRequiredTitle: 'Accès administrateur requis', adminRequiredText: 'La gestion des produits est réservée aux comptes administrateurs.',
    productInfoTitle: 'Informations du produit', productInfoSubtitleEdit: 'Modifiez la fiche produit et enregistrez les changements.', productInfoSubtitleCreate: "Renseignez l'identité complète du produit comme sur le web.",
    productName: 'Nom du produit', productNamePlaceholder: 'Ex: Riz parfumé', barcode: 'Code-barres', barcodePlaceholder: 'Scannez ou saisissez le code', scan: 'Scanner', category: 'Catégorie', chooseCategory: 'Choisir une catégorie', supplier: 'Fournisseur', loading: 'Chargement...', chooseSupplier: 'Choisir un fournisseur', noSupplier: 'Aucun fournisseur', description: 'Description', descriptionPlaceholder: 'Description optionnelle du produit...',
    stockTypeTitle: 'Type de produit & stock', stockTypeSubtitle: 'Commence ici : choisis comment tu veux enregistrer le produit.', manualEntry: 'Produit simple', manualEntryDesc: "Tu saisis directement le prix, le stock et l'unité de base.", automaticInfo: "Tu renseignes le conditionnement commercial et l'app calcule automatiquement les données de base.", modeGuideTitle: 'Comment ça marche', manualModeGuide: "Choisis Produit simple si tu vends déjà à l'unité, au paquet ou au mètre sans conversion automatique.", automaticModeGuide: (label) => `Choisis ${label} si tu gères un stock en sac, bidon ou carton. L'app convertit automatiquement le stock et les prix de base.`, detailUnitPrice: 'Prix unitaire détaillé (optionnel)', autoIfEmpty: 'Calcul auto si vide', autoPreview: 'Aperçu automatique', internalBase: 'Base interne', computedStock: 'Stock calculé', detailUnits: 'Unités détaillées', salePrice: "Prix de vente (FCFA)", purchasePrice: "Prix d'achat (FCFA)", initialStock: "Stock initial", alertStock: 'Stock d\'alerte', saleUnitsTitle: 'Unités de vente (conversions)', saleUnitsSubtitle: 'Optionnel : ajoute ici les formats de vente supplémentaires (sac, carton, lot...).', saleUnitsInfoTitle: 'Facultatif', saleUnitsInfo: (baseUnit) => `Tu peux enregistrer le produit sans remplir cette partie. Ajoute-la seulement si tu veux vendre ce produit dans plusieurs unités à partir de ${baseUnit}.`, quickSuggestions: 'Suggestions rapides', addUnit: 'Ajouter une unité', unitName: "Nom de l'unité", unitNamePlaceholder: 'Ex: Sac 50kg', conversionFactor: 'Facteur de conversion', conversionFactorPlaceholder: 'Ex: 50000', unitSalePrice: 'Prix vente (FCFA)', setDefault: 'Définir par défaut', defaultUnit: 'Unité par défaut', removeUnit: 'Supprimer', noUnitsTitle: 'Aucune unité de vente définie', noUnitsText: 'Ajoutez des unités pour vendre en sac, kg, carton, lot, etc.', incompleteUnit: "Complète ou retire la ligne d'unité de vente incomplète avant d'enregistrer.", duplicateUnit: (name) => `${name} existe déjà.`, stockEquivalences: 'Équivalences du stock', saleUnitsSummary: 'Conversions prêtes à vendre', configuredUnits: (count) => `${count} unité(s) configurée(s)`, unitPriceLabel: 'Prix',
    expirationTitle: 'Péremption & alertes', expirationSubtitle: "Ajoutez une date de péremption simple et un seuil d'alerte en jours.", expirationDate: 'Date de péremption', expirationDatePlaceholder: 'Choisir une date', expirationDayLabel: 'Jour', expirationMonthFieldLabel: 'Mois', expirationYearLabel: 'Année', expirationAlertDays: 'Alerte avant (jours)', expirationAlertDaysPlaceholder: '30 = 30 jours avant', expirationHint: "Laissez vide si le produit n'a pas de date de péremption.", expirationDateRequired: 'Renseignez une date de péremption avant de définir une alerte.', expirationInvalid: 'La date de péremption doit être au format AAAA-MM-JJ.', expirationAlertInvalid: "Le seuil d'alerte de péremption doit être un nombre positif ou nul.", expirationSummary: 'Péremption', expirationConfirm: 'Valider', expirationClear: 'Effacer', noExpiration: 'Non définie', expiresOn: (date) => `Expire le ${date}`, expiresIn: (date, days) => `Expire le ${date} (dans ${days} j)`, expiredSince: (date, days) => `Expiré depuis ${days} j (${date})`,
    summaryTitle: 'Résumé avant enregistrement', summarySubtitle: "Dernière vérification avant d'enregistrer le produit.", baseUnit: 'Unité de base', mode: 'Mode', stockSaved: 'Stock enregistré', undefinedCategory: 'Non définie', undefinedSupplier: 'Non défini', estimatedMargin: (value) => `Marge estimée : ${value}%`, saveHelperTitle: 'Ce qui sera enregistré', saveHelperManual: 'Le produit sera enregistré avec son prix, son stock et son unité de base.', saveHelperManualUnits: (count) => count > 0 ? `${count} unité(s) de vente supplémentaire(s) seront aussi enregistrée(s).` : 'Aucune unité de vente supplémentaire ne sera ajoutée.', saveHelperAutomatic: (stock, unit) => `L'app convertira automatiquement le conditionnement vers ${stock} ${unit} en stock de base.`, saveHelperEdit: 'Tu pourras modifier ces informations plus tard depuis le stock.', saveChanges: 'Enregistrer ces modifications', saveProduct: 'Enregistrer ce produit', scanHint: 'Scannez le code-barres du produit', cameraDenied: 'Permission caméra non accordée.', close: 'Fermer', chooseCategoryTitle: 'Choisir une catégorie', chooseSupplierTitle: 'Choisir un fournisseur', noSelection: 'Aucune sélection',
  },
  en: {
    unitLabels: { g: 'Gram (g)', ml: 'Milliliter (ml)', piece: 'Piece', paquet: 'Pack', m: 'Meter (m)' },
    flowTexts: {
      poids: { title: 'Product sold by bag / weight', description: 'Rice, sugar, flour, cereals…', packLabel: 'Bag', packLabelPlural: 'bags', sizeLabel: 'Weight of one bag', countLabel: 'Number of bags in stock', alertLabel: 'Alert threshold (in bags)', saleLabel: 'Sale price per bag', purchaseLabel: 'Purchase price per bag' },
      volume: { title: 'Product sold by container / volume', description: 'Oil, milk, water, juice…', packLabel: 'Container', packLabelPlural: 'containers', sizeLabel: 'Volume of one container', countLabel: 'Number of containers in stock', alertLabel: 'Alert threshold (in containers)', saleLabel: 'Sale price per container', purchaseLabel: 'Purchase price per container' },
      carton: { title: 'Product sold by carton', description: 'Spaghetti, biscuits, packs…', packLabel: 'Carton', packLabelPlural: 'cartons', sizeLabel: 'Units in one carton', countLabel: 'Number of cartons in stock', alertLabel: 'Alert threshold (in cartons)', saleLabel: 'Sale price per carton', purchaseLabel: 'Purchase price per carton' },
    },
    error: 'Error', editTitle: 'Edit product', createTitle: 'New product', loadTitle: 'Loading failed', loadError: 'Unable to load the product.', back: 'Back',
    cameraPermissionTitle: 'Camera permission', cameraPermissionText: 'Allow the camera to scan the product barcode.',
    accessDenied: 'Access denied', adminOnly: (isEditing) => `Only an administrator can ${isEditing ? 'edit' : 'create'} a product.`, requiredField: 'Required field',
    requiredName: 'Please enter the product name.', requiredBarcode: 'Please enter or scan a barcode.', requiredSize: 'Please enter the package size.', requiredPackSale: 'Please enter the package sale price.', requiredPackPurchase: 'Please enter the package purchase price.', requiredSale: 'Please enter the sale price.',
    updatedTitle: 'Product updated', createdTitle: 'Product created', updatedMessage: (name) => `${name} was updated successfully.`, createdMessage: (name) => `${name} was saved successfully.`, backToStock: 'Back to stock', createAnother: 'Create another', viewStock: 'View stock', viewPlans: 'View plans', saveError: (isEditing) => `Unable to ${isEditing ? 'update' : 'create'} the product.`,
    adminRequiredTitle: 'Administrator access required', adminRequiredText: 'Product management is reserved for administrator accounts.',
    productInfoTitle: 'Product information', productInfoSubtitleEdit: 'Edit the product sheet and save your changes.', productInfoSubtitleCreate: 'Enter the full product identity just like on the web app.',
    productName: 'Product name', productNamePlaceholder: 'Ex: Fragrant rice', barcode: 'Barcode', barcodePlaceholder: 'Scan or enter the code', scan: 'Scan', category: 'Category', chooseCategory: 'Choose a category', supplier: 'Supplier', loading: 'Loading...', chooseSupplier: 'Choose a supplier', noSupplier: 'No supplier', description: 'Description', descriptionPlaceholder: 'Optional product description...',
    stockTypeTitle: 'Product type & stock', stockTypeSubtitle: 'Start here: choose how you want to save the product.', manualEntry: 'Simple product', manualEntryDesc: 'You enter the price, stock and base unit directly.', automaticInfo: 'You enter the commercial packaging and the app automatically calculates the base data.', modeGuideTitle: 'How it works', manualModeGuide: 'Choose Simple product if you already sell the item directly by piece, pack or meter without automatic conversion.', automaticModeGuide: (label) => `Choose ${label} if you manage stock in bags, containers or cartons. The app automatically converts stock and base prices.`, detailUnitPrice: 'Detailed unit price (optional)', autoIfEmpty: 'Auto-calculated if empty', autoPreview: 'Automatic preview', internalBase: 'Internal base', computedStock: 'Computed stock', detailUnits: 'Detailed units', salePrice: 'Sale price (FCFA)', purchasePrice: 'Purchase price (FCFA)', initialStock: 'Initial stock', alertStock: 'Alert stock', saleUnitsTitle: 'Sales units (conversions)', saleUnitsSubtitle: 'Optional: add extra selling formats here (bag, carton, bundle...).', saleUnitsInfoTitle: 'Optional', saleUnitsInfo: (baseUnit) => `You can save the product without filling this part. Use it only if you want to sell this product in several units based on ${baseUnit}.`, quickSuggestions: 'Quick suggestions', addUnit: 'Add a unit', unitName: 'Unit name', unitNamePlaceholder: 'Ex: 50kg bag', conversionFactor: 'Conversion factor', conversionFactorPlaceholder: 'Ex: 50000', unitSalePrice: 'Sale price (FCFA)', setDefault: 'Set as default', defaultUnit: 'Default unit', removeUnit: 'Remove', noUnitsTitle: 'No sales unit defined', noUnitsText: 'Add units to sell in bags, kg, cartons, bundles, etc.', incompleteUnit: 'Complete or remove the incomplete sales-unit row before saving.', duplicateUnit: (name) => `${name} already exists.`, stockEquivalences: 'Stock equivalents', saleUnitsSummary: 'Ready-to-sell conversions', configuredUnits: (count) => `${count} configured unit(s)`, unitPriceLabel: 'Price',
    expirationTitle: 'Expiration & alerts', expirationSubtitle: 'Add a simple expiration date and an alert threshold in days.', expirationDate: 'Expiration date', expirationDatePlaceholder: 'Choose a date', expirationDayLabel: 'Day', expirationMonthFieldLabel: 'Month', expirationYearLabel: 'Year', expirationAlertDays: 'Alert before (days)', expirationAlertDaysPlaceholder: '30 = 30 days before', expirationHint: 'Leave blank if the product has no expiration date.', expirationDateRequired: 'Enter an expiration date before defining an alert.', expirationInvalid: 'The expiration date must use the YYYY-MM-DD format.', expirationAlertInvalid: 'The expiration alert threshold must be a positive or zero number.', expirationSummary: 'Expiration', expirationConfirm: 'Confirm', expirationClear: 'Clear', noExpiration: 'Not set', expiresOn: (date) => `Expires on ${date}`, expiresIn: (date, days) => `Expires on ${date} (in ${days} d)`, expiredSince: (date, days) => `Expired ${days} d ago (${date})`,
    summaryTitle: 'Summary before saving', summarySubtitle: 'Final check before saving the product.', baseUnit: 'Base unit', mode: 'Mode', stockSaved: 'Recorded stock', undefinedCategory: 'Not defined', undefinedSupplier: 'Not defined', estimatedMargin: (value) => `Estimated margin: ${value}%`, saveHelperTitle: 'What will be saved', saveHelperManual: 'The product will be saved with its price, stock and base unit.', saveHelperManualUnits: (count) => count > 0 ? `${count} extra sales unit(s) will also be saved.` : 'No extra sales unit will be added.', saveHelperAutomatic: (stock, unit) => `The app will automatically convert the packaging into ${stock} ${unit} of base stock.`, saveHelperEdit: 'You can edit this later from stock.', saveChanges: 'Save these changes', saveProduct: 'Save this product', scanHint: 'Scan the product barcode', cameraDenied: 'Camera permission not granted.', close: 'Close', chooseCategoryTitle: 'Choose a category', chooseSupplierTitle: 'Choose a supplier', noSelection: 'No selection',
  },
};
